language: python
os: linux
dist: xenial
git:
    submodules: true
cache:
    directories:
        - $HOME/.local/bin
        - $HOME/.stack
python:
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"
install:
    - if [ ! -f .local/bin/stack ]; then sudo curl -sSL https://get.haskellstack.org/ | sh; fi
    - if [ ! -f .stack/programs/x86_64-linux/ghc-tinfo-8.8.3/bin/ghc ]; then stack install ghc; fi
    - stack --version
    - pip install -r requirements.txt
    - python -m pip install --ignore-installed -r requirements-dev.txt
script:
    - python -c "import pythas; import test.hs.testcases"
    - pytest

